In [1]:
from __future__ import print_function, division

from keras.datasets import mnist
from keras.layers import Input, Dense, Reshape, Flatten, Dropout, Bidirectional, LSTM, Reshape, RepeatVector, TimeDistributed
from keras.layers import BatchNormalization, Activation
from keras.layers.advanced_activations import LeakyReLU
from keras.layers.convolutional import UpSampling2D, Conv2D
from keras.models import Sequential, Model
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import StandardScaler
import tensorflow_gan as tfgan
import tensorflow as tf
tf.compat.v1.enable_eager_execution() 

import matplotlib.pyplot as plt

import sys

import numpy as np
import pandas as pd

import os

from PIL import Image

# Load Data
Loading from preprocessed numpy array

In [45]:
def load_data():
    x_train = np.array(pd.read_csv("./data_stock/SP500_average.csv",).drop([0]).drop(columns=['Date']))
    return x_train
            

def split_time_series(t, arr) -> (np.array, np.array):
    a = []
    b = []
    for i in range(len(arr)-t):
        a.append(arr[i: i+t])
        b.append(arr[i+t])
    return (np.array(a), np.array(b))
    

def merge_time_series(arr1, arr2) -> tf.float64 :
    t1 = tf.cast(arr1, 'float64') if tf.is_tensor(arr1) else tf.convert_to_tensor(arr1, dtype='float64')
    t2 = tf.cast(arr2, 'float64') if tf.is_tensor(arr2) else tf.convert_to_tensor(arr2, dtype='float64')
    return tf.concat([t1, tf.expand_dims(t2, 1) ], axis=1)

def standardize_time_series(arr1):
    scaler = StandardScaler()
    scaler.fit(arr1)
    return (scaler.transform(arr1), scaler)
                                
(input, output) = split_time_series(5, load_data())
merged = merge_time_series(input, output)

print(input)
print(output)
print(merged)

[[[4366.64 4411.01 4287.11 4356.45]
  [4356.32 4417.35 4222.62 4410.13]
  [4471.38 4494.52 4395.34 4397.94]
  [4547.35 4602.11 4477.95 4482.73]
  [4588.03 4611.55 4530.2  4532.76]]

 [[4356.32 4417.35 4222.62 4410.13]
  [4471.38 4494.52 4395.34 4397.94]
  [4547.35 4602.11 4477.95 4482.73]
  [4588.03 4611.55 4530.2  4532.76]
  [4632.24 4632.24 4568.7  4577.11]]

 [[4471.38 4494.52 4395.34 4397.94]
  [4547.35 4602.11 4477.95 4482.73]
  [4588.03 4611.55 4530.2  4532.76]
  [4632.24 4632.24 4568.7  4577.11]
  [4637.99 4665.13 4614.75 4662.85]]

 ...

 [[2457.77 2571.42 2407.53 2475.56]
  [2344.44 2449.71 2344.44 2447.33]
  [2290.71 2300.73 2191.86 2237.4 ]
  [2431.94 2453.01 2295.56 2304.92]
  [2393.48 2466.97 2319.78 2409.39]]

 [[2344.44 2449.71 2344.44 2447.33]
  [2290.71 2300.73 2191.86 2237.4 ]
  [2431.94 2453.01 2295.56 2304.92]
  [2393.48 2466.97 2319.78 2409.39]
  [2436.5  2453.57 2280.52 2398.1 ]]

 [[2290.71 2300.73 2191.86 2237.4 ]
  [2431.94 2453.01 2295.56 2304.92]
  [2393.48 2

# Creating GAN

In [76]:
class LSTMGAN():
    def __init__(self, t, f, data):
        self.data = data
        self.time_series_len = t
        self.feature_len = f
        self.gen_shape = (self.time_series_len, self.feature_len)
        self.dis_shape = (self.time_series_len+1, self.feature_len)

        optimizer = Adam(0.0001, 0.4)

        # Build and compile the discriminator
        self.discriminator = self.build_discriminator()
        self.discriminator.compile(loss='binary_crossentropy',
            optimizer=optimizer,
            metrics=['accuracy'])

        # Build the generator
        self.generator = self.build_generator()
        # Trains the generator to imitate input data
        self.generator.compile(loss='mean_squared_error',
            optimizer=optimizer)
        
        # The generator takes noise as input and generates song
        noise = Input(shape=self.gen_shape)
        gen_output = self.generator(noise)
        # For the combined model we will only train the generator
        self.discriminator.trainable = False

        # The discriminator takes generated images as input and determines validity
        valid = self.discriminator(merge_time_series(noise, gen_output))

        # The combined model  (stacked generator and discriminator)
        # Trains the generator to fool the discriminator
        self.combined = Model(noise, valid)
        
        self.combined.compile(loss='binary_crossentropy', optimizer=optimizer)
        
        

    def build_generator(self):

        model = Sequential()
        model.add(Bidirectional(LSTM(128, return_sequences=True), input_shape=self.gen_shape))
        model.add(LeakyReLU(alpha=0.2))
        model.add(Dropout(0.2))
        model.add(Bidirectional(LSTM(128)))
        model.add(LeakyReLU(alpha=0.2))
        model.add(Dense(4))
        # model.summary()

        noise = Input(shape=self.gen_shape)
        img = model(noise)

        return Model(noise, img)

    def build_discriminator(self):

        model = Sequential()
        
        model.add(Bidirectional(LSTM(128, activation = 'relu', return_sequences=True), input_shape=self.dis_shape))
        model.add(Dropout(0.4))
        model.add(TimeDistributed(Dense(128, activation = 'relu')))
        model.add(Dense(1, activation = 'linear'))
        #model.summary()

        img = Input(shape=self.dis_shape)
        validity = model(img)

        return Model(img, validity)
    
    
    def train(self, epochs, batch_size=128, save_interval=50):

        # Load the dataset
        (X_train_input, X_train_output) = split_time_series(self.time_series_len, self.data)

        # normalize

        # Adversarial ground truths
        valid = np.ones(batch_size)
        fake = np.zeros(batch_size)

        for epoch in range(epochs):

            # ---------------------
            #  Train Discriminator
            # -------------------)--
            # Select a random half of songs
            idx = np.random.randint(0, X_train_input.shape[0], batch_size)
            real_input= X_train_input[idx]
            real_output= X_train_output[idx]
            
            #standardize data
            def standardize_fn(input_t, output_t) : 
                scaler = StandardScaler();
                scaler.fit(input_t)
                return (scaler.transform(input_t), scaler.transform([output_t])[0], scaler)
            
            zipped = [ standardize_fn(i, o) for (i, o) in zip(real_input, real_output)]
            (real_input, real_output, scalers) = zip(*zipped)
            
            # Sample noise and generate a batch of new prices
            noise = np.random.normal(0, 1, (batch_size,self.time_series_len,self.feature_len))
            gen_output = self.generator.predict(noise, batch_size = batch_size)
            real_series = merge_time_series(real_input,real_output)
            fake_series = merge_time_series(real_input,gen_output)
            print("input:\n", scalers[0].inverse_transform( real_input[0]))
            print("fake_output:\n", scalers[0].inverse_transform( [gen_output[0]]))
            print("real_output:\n", scalers[0].inverse_transform( [real_output[0]]))

            # Train the discriminator (real classified as ones and generated as zeros)
            d_loss_real = self.discriminator.train_on_batch(real_series, valid)
            d_loss_fake = self.discriminator.train_on_batch(fake_series, fake)
            d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)

            # ---------------------
            #  Train Generator
            # ---------------------
            # First training (wants generator to imitate real data)
            #g_loss1 = self.generator.train_on_batch( np.array(real_input), np.array(real_output))
            
            # Second training (wants discriminator to mistake songs as real)
            #g_loss2 = self.combined.train_on_batch(noise, valid)
            #g_loss = 0.5 * np.add(g_loss1, g_loss2)
            g_loss = self.combined.train_on_batch(noise, valid)



            # Plot the progress
            print ("%d [D loss: %f, acc.: %.2f%%] [G loss: %f]" % (epoch, d_loss[0], 100*d_loss[1], g_loss))

            # If at save interval => save model
            if epoch % save_interval == 0:
                self.generator.save("LSTM_generator.h5")

# Model Summary
I couldn't train the model on this online notebook so I trained it locally for 1000 epochs and uploaded the h5 file.

In [77]:
lstmgan = LSTMGAN(5, 4, load_data())
lstmgan.train(epochs=1000, batch_size=50, save_interval=100)

input:
 [[2578.28 2676.85 2574.57 2663.68]
 [2514.92 2538.18 2459.96 2488.65]
 [2458.54 2533.22 2455.79 2526.9 ]
 [2498.08 2522.75 2447.49 2470.5 ]
 [2614.69 2641.39 2571.15 2584.59]]
fake_output:
 [[2532.80157862 2582.31648315 2503.2647609  2546.65819059]]
real_output:
 [[2558.98 2631.8  2545.28 2626.65]]
0 [D loss: 5.193274, acc.: 50.00%] [G loss: 7.019440]
input:
 [[4477.09 4485.87 4443.8  4473.75]
 [4447.49 4486.87 4438.37 4480.7 ]
 [4479.33 4485.68 4435.46 4443.05]
 [4474.81 4492.99 4445.7  4468.73]
 [4506.92 4520.47 4457.66 4458.58]]
fake_output:
 [[4477.16599024 4494.03553023 4444.28321356 4464.86181748]]
real_output:
 [[4513.02 4529.9  4492.07 4493.28]]
1 [D loss: 4.099460, acc.: 50.00%] [G loss: 6.206120]
input:
 [[3371.88 3379.97 3329.27 3331.84]
 [3453.6  3479.15 3349.63 3426.96]
 [3564.74 3564.85 3427.41 3455.06]
 [3543.76 3588.11 3535.23 3580.84]
 [3507.44 3528.03 3494.6  3526.65]]
fake_output:
 [[3488.74738153 3507.92944082 3428.54601833 3464.67041259]]
real_output:
 [[35

22 [D loss: 1.110656, acc.: 50.00%] [G loss: 2.136855]
input:
 [[3566.82 3589.81 3552.77 3577.59]
 [3579.31 3581.23 3556.85 3557.54]
 [3559.41 3585.22 3543.84 3581.87]
 [3612.09 3619.09 3567.33 3567.79]
 [3610.31 3623.11 3588.68 3609.53]]
fake_output:
 [[3585.71576386 3599.37937721 3564.16196517 3579.28270469]]
real_output:
 [[3600.16 3628.51 3600.16 3626.91]]
23 [D loss: 1.078706, acc.: 50.00%] [G loss: 2.089335]
input:
 [[4415.95 4416.17 4400.23 4402.66]
 [4392.74 4423.79 4373.   4423.15]
 [4406.86 4422.18 4384.81 4387.16]
 [4395.12 4412.25 4389.65 4395.26]
 [4403.59 4429.97 4403.59 4419.15]]
fake_output:
 [[4402.9459984  4420.59499252 4391.66604673 4405.91812363]]
real_output:
 [[4402.95 4415.47 4387.01 4400.64]]
24 [D loss: 1.075640, acc.: 50.00%] [G loss: 2.054240]
input:
 [[2829.95 2865.01 2816.78 2863.7 ]
 [2794.54 2852.8  2766.64 2852.5 ]
 [2865.86 2874.14 2793.15 2820.  ]
 [2939.5  2945.82 2869.59 2870.12]
 [2915.46 2944.25 2903.44 2930.32]]
fake_output:
 [[2870.45121788 2895.

input:
 [[3552.57 3593.66 3552.57 3585.15]
 [3562.67 3569.02 3518.58 3537.01]
 [3563.22 3581.16 3557.   3572.66]
 [3543.26 3557.22 3511.91 3545.53]
 [3583.04 3645.99 3547.48 3550.5 ]]
fake_output:
 [[3560.57647683 3586.53004718 3543.42917206 3560.00838806]]
real_output:
 [[3508.34 3521.58 3484.34 3509.44]]
46 [D loss: 0.874573, acc.: 50.67%] [G loss: 1.656256]
input:
 [[3350.92 3357.92 3327.54 3335.47]
 [3333.9  3360.74 3332.91 3351.6 ]
 [3236.66 3306.88 3228.44 3298.46]
 [3226.14 3278.7  3209.45 3246.59]
 [3320.11 3323.35 3232.57 3236.92]]
fake_output:
 [[3294.34329202 3323.14752324 3284.84002207 3299.38062435]]
real_output:
 [[3295.75 3320.31 3270.95 3315.57]]
47 [D loss: 0.868421, acc.: 50.50%] [G loss: 1.673684]
input:
 [[4578.69 4598.53 4569.17 4574.79]
 [4553.69 4572.62 4537.36 4566.48]
 [4546.12 4559.67 4524.   4544.9 ]
 [4532.24 4551.44 4526.89 4549.78]
 [4524.42 4540.87 4524.4  4536.19]]
fake_output:
 [[4547.29975739 4562.98239873 4541.77566355 4555.79402164]]
real_output:
 [[

69 [D loss: 0.768850, acc.: 52.00%] [G loss: 1.350172]
input:
 [[2939.5  2945.82 2869.59 2870.12]
 [2915.46 2944.25 2903.44 2930.32]
 [2908.83 2932.16 2902.88 2929.8 ]
 [2878.26 2901.92 2876.48 2881.19]
 [2883.14 2891.11 2847.65 2848.42]]
fake_output:
 [[2905.65487398 2909.72227182 2916.34556853 2916.18679339]]
real_output:
 [[2868.88 2898.23 2863.55 2868.44]]
70 [D loss: 0.787232, acc.: 51.50%] [G loss: 1.328577]
input:
 [[4368.31 4374.89 4342.09 4350.65]
 [4385.44 4415.88 4360.59 4361.19]
 [4406.51 4412.02 4386.22 4391.34]
 [4383.73 4429.97 4383.73 4399.76]
 [4319.57 4365.57 4290.49 4363.55]]
fake_output:
 [[4373.99601064 4367.85692504 4468.92799084 4404.29698709]]
real_output:
 [[4309.87 4369.23 4309.87 4345.72]]
71 [D loss: 0.756128, acc.: 52.17%] [G loss: 1.304804]
input:
 [[3131.   3153.45 3076.06 3124.74]
 [2993.76 3079.76 2965.66 3066.59]
 [3071.04 3088.42 2984.47 3041.31]
 [3123.53 3123.53 2999.49 3002.1 ]
 [3213.42 3223.27 3181.49 3190.14]]
fake_output:
 [[3108.72855211 3082.

input:
 [[4403.59 4429.97 4403.59 4419.15]
 [4402.95 4415.47 4387.01 4400.64]
 [4416.38 4416.38 4372.51 4401.46]
 [4409.58 4422.73 4405.45 4422.3 ]
 [4381.2  4415.18 4381.2  4411.79]]
fake_output:
 [[4396.5569941  4409.68742297 4513.76962097 4459.53672742]]
real_output:
 [[4361.27 4369.87 4350.06 4367.48]]
93 [D loss: 0.926094, acc.: 41.67%] [G loss: 0.882883]
input:
 [[4096.11 4129.48 4095.51 4128.8 ]
 [4089.95 4098.19 4082.54 4097.17]
 [4074.29 4083.13 4068.31 4079.95]
 [4075.57 4086.23 4068.14 4073.94]
 [4034.44 4083.42 4034.44 4077.91]]
fake_output:
 [[4059.18393615 4062.64352008 4296.49309301 4219.83442304]]
real_output:
 [[3992.78 4020.63 3992.78 4019.87]]
94 [D loss: 0.887904, acc.: 41.00%] [G loss: 0.879366]
input:
 [[3508.34 3521.58 3484.34 3509.44]
 [3485.74 3529.05 3485.74 3510.45]
 [3406.46 3486.25 3405.17 3443.44]
 [3336.25 3389.49 3336.25 3369.16]
 [3296.2  3330.14 3279.74 3310.24]]
fake_output:
 [[3341.38307066 3301.13524743 4405.11848311 3985.3443475 ]]
real_output:
 [[

input:
 [[4471.38 4494.52 4395.34 4397.94]
 [4547.35 4602.11 4477.95 4482.73]
 [4588.03 4611.55 4530.2  4532.76]
 [4632.24 4632.24 4568.7  4577.11]
 [4637.99 4665.13 4614.75 4662.85]]
fake_output:
 [[4427.62367262 4628.29820811 5498.13523703 5214.92968413]]
real_output:
 [[4733.56 4744.13 4650.29 4659.03]]
116 [D loss: 0.664555, acc.: 54.00%] [G loss: 1.670066]
input:
 [[3543.76 3588.11 3535.23 3580.84]
 [3507.44 3528.03 3494.6  3526.65]
 [3509.73 3514.77 3493.25 3500.31]
 [3494.69 3509.23 3484.32 3508.01]
 [3485.14 3501.38 3468.35 3484.55]]
fake_output:
 [[3460.023961   3546.60549961 3773.48875819 3769.45086859]]
real_output:
 [[3449.97 3481.07 3444.15 3478.73]]
117 [D loss: 0.660782, acc.: 55.50%] [G loss: 1.673678]
input:
 [[4138.78 4194.17 4138.78 4180.17]
 [4170.46 4179.57 4123.69 4134.98]
 [4128.42 4175.02 4126.35 4173.42]
 [4159.18 4159.18 4118.38 4134.94]
 [4179.8  4180.81 4150.47 4163.26]]
fake_output:
 [[4110.76740718 4185.51019533 4265.71206482 4287.64540671]]
real_output:
 

138 [D loss: 0.591287, acc.: 65.83%] [G loss: 1.324142]
input:
 [[3453.6  3479.15 3349.63 3426.96]
 [3564.74 3564.85 3427.41 3455.06]
 [3543.76 3588.11 3535.23 3580.84]
 [3507.44 3528.03 3494.6  3526.65]
 [3509.73 3514.77 3493.25 3500.31]]
fake_output:
 [[3489.50886877 3559.21996142 3635.43393007 3580.44531567]]
real_output:
 [[3494.69 3509.23 3484.32 3508.01]]
139 [D loss: 0.592253, acc.: 65.33%] [G loss: 1.280400]
input:
 [[3406.46 3486.25 3405.17 3443.44]
 [3336.25 3389.49 3336.25 3369.16]
 [3296.2  3330.14 3279.74 3310.24]
 [3293.59 3304.93 3233.94 3269.96]
 [3277.17 3341.05 3259.82 3310.11]]
fake_output:
 [[3272.42217476 3438.40928101 3554.92452967 3479.41149038]]
real_output:
 [[3342.48 3342.48 3268.89 3271.03]]
140 [D loss: 0.593409, acc.: 66.67%] [G loss: 1.291468]
input:
 [[3406.46 3486.25 3405.17 3443.44]
 [3336.25 3389.49 3336.25 3369.16]
 [3296.2  3330.14 3279.74 3310.24]
 [3293.59 3304.93 3233.94 3269.96]
 [3277.17 3341.05 3259.82 3310.11]]
fake_output:
 [[3258.15385924 34

input:
 [[4274.45 4286.12 4271.16 4280.7 ]
 [4256.97 4271.28 4256.97 4266.49]
 [4249.27 4256.6  4241.43 4241.84]
 [4224.61 4255.84 4217.27 4246.44]
 [4173.4  4226.24 4173.4  4224.79]]
fake_output:
 [[4218.70499287 4270.97228111 4297.3318499  4272.19951465]]
real_output:
 [[4204.78 4204.78 4164.4  4166.45]]
162 [D loss: 0.559892, acc.: 78.17%] [G loss: 1.158449]
input:
 [[3071.04 3088.42 2984.47 3041.31]
 [3123.53 3123.53 2999.49 3002.1 ]
 [3213.42 3223.27 3181.49 3190.14]
 [3213.32 3222.71 3193.11 3207.18]
 [3199.92 3233.13 3196.   3232.39]]
fake_output:
 [[3123.30946167 3243.19947649 3406.9879518  3283.25854634]]
real_output:
 [[3163.84 3211.72 3163.84 3193.93]]
163 [D loss: 0.581461, acc.: 73.33%] [G loss: 1.109882]
input:
 [[4613.34 4635.15 4613.34 4630.65]
 [4610.62 4620.34 4595.06 4613.67]
 [4572.87 4608.08 4567.59 4605.38]
 [4562.84 4597.55 4562.84 4596.42]
 [4580.22 4584.57 4551.66 4551.68]]
fake_output:
 [[4572.3775561  4628.47249799 4650.08634931 4643.04044724]]
real_output:
 

184 [D loss: 0.544222, acc.: 74.83%] [G loss: 0.986507]
input:
 [[4385.44 4415.88 4360.59 4361.19]
 [4406.51 4412.02 4386.22 4391.34]
 [4383.73 4429.97 4383.73 4399.76]
 [4319.57 4365.57 4290.49 4363.55]
 [4309.87 4369.23 4309.87 4345.72]]
fake_output:
 [[4346.83903583 4424.03573399 4422.60020975 4389.69345924]]
real_output:
 [[4348.84 4355.51 4278.94 4300.46]]
185 [D loss: 0.554568, acc.: 74.33%] [G loss: 1.086502]
input:
 [[3234.27 3243.72 3216.17 3218.44]
 [3219.84 3241.43 3214.25 3239.41]
 [3218.58 3227.26 3200.05 3215.63]
 [3271.64 3279.99 3222.66 3235.66]
 [3254.86 3279.32 3253.1  3276.02]]
fake_output:
 [[3232.7003136  3269.4428488  3249.67408387 3254.44414555]]
real_output:
 [[3268.52 3277.29 3247.77 3257.3 ]]
186 [D loss: 0.515434, acc.: 78.67%] [G loss: 1.068384]
input:
 [[3534.01 3534.01 3500.86 3511.93]
 [3500.02 3549.85 3499.61 3534.22]
 [3459.67 3482.34 3458.07 3477.13]
 [3434.28 3447.28 3428.15 3446.83]
 [3384.56 3426.26 3384.56 3419.45]]
fake_output:
 [[3440.75034197 35

input:
 [[4553.69 4572.62 4537.36 4566.48]
 [4546.12 4559.67 4524.   4544.9 ]
 [4532.24 4551.44 4526.89 4549.78]
 [4524.42 4540.87 4524.4  4536.19]
 [4497.34 4520.4  4496.41 4519.63]]
fake_output:
 [[4528.67398087 4562.73619079 4536.87220228 4550.15294437]]
real_output:
 [[4463.72 4488.75 4447.47 4486.46]]
208 [D loss: 0.524544, acc.: 72.67%] [G loss: 0.923350]
input:
 [[4477.09 4485.87 4443.8  4473.75]
 [4447.49 4486.87 4438.37 4480.7 ]
 [4479.33 4485.68 4435.46 4443.05]
 [4474.81 4492.99 4445.7  4468.73]
 [4506.92 4520.47 4457.66 4458.58]]
fake_output:
 [[4474.19399704 4506.5613617  4454.97695336 4473.25018033]]
real_output:
 [[4513.02 4529.9  4492.07 4493.28]]
209 [D loss: 0.541178, acc.: 71.33%] [G loss: 0.986098]
input:
 [[4699.26 4718.5  4681.32 4697.53]
 [4662.93 4683.   4662.59 4680.06]
 [4630.65 4663.46 4621.19 4660.57]
 [4613.34 4635.15 4613.34 4630.65]
 [4610.62 4620.34 4595.06 4613.67]]
fake_output:
 [[4638.27635455 4691.22282586 4674.47469839 4673.71887903]]
real_output:
 

230 [D loss: 0.566916, acc.: 67.33%] [G loss: 0.965252]
input:
 [[4121.97 4172.8  4121.97 4159.12]
 [4098.45 4116.93 4061.41 4115.68]
 [4165.94 4169.15 4125.99 4127.83]
 [4169.92 4171.92 4142.69 4163.29]
 [4129.58 4183.13 4129.58 4173.85]]
fake_output:
 [[4145.67628225 4198.81265853 4137.24824087 4150.50591865]]
real_output:
 [[4074.99 4131.58 4074.99 4112.5 ]]
231 [D loss: 0.549914, acc.: 70.50%] [G loss: 0.917671]
input:
 [[2685.   2760.75 2663.3  2749.98]
 [2738.65 2756.89 2657.67 2659.41]
 [2578.28 2676.85 2574.57 2663.68]
 [2514.92 2538.18 2459.96 2488.65]
 [2458.54 2533.22 2455.79 2526.9 ]]
fake_output:
 [[2628.57523276 2828.26831717 2650.75444469 2635.89651597]]
real_output:
 [[2498.08 2522.75 2447.49 2470.5 ]]
232 [D loss: 0.567404, acc.: 66.67%] [G loss: 0.909457]
input:
 [[3920.78 3931.5  3884.94 3909.88]
 [3910.49 3918.35 3902.64 3911.23]
 [3892.59 3915.77 3892.59 3915.59]
 [3878.3  3894.56 3874.93 3886.83]
 [3836.66 3872.42 3836.66 3871.74]]
fake_output:
 [[3895.49489579 39

253 [D loss: 0.570114, acc.: 64.00%] [G loss: 0.876956]
input:
 [[2993.76 3079.76 2965.66 3066.59]
 [3071.04 3088.42 2984.47 3041.31]
 [3123.53 3123.53 2999.49 3002.1 ]
 [3213.42 3223.27 3181.49 3190.14]
 [3213.32 3222.71 3193.11 3207.18]]
fake_output:
 [[3182.02572307 3252.38724172 3076.29813191 3091.60655555]]
real_output:
 [[3199.92 3233.13 3196.   3232.39]]
254 [D loss: 0.585247, acc.: 62.33%] [G loss: 0.903165]
input:
 [[3693.42 3711.24 3689.28 3690.01]
 [3698.08 3698.26 3676.16 3687.26]
 [3684.28 3702.9  3636.48 3694.92]
 [3722.39 3726.7  3685.84 3709.41]
 [3713.65 3725.12 3710.87 3722.48]]
fake_output:
 [[3716.39919005 3742.77416571 3686.7850871  3698.71263416]]
real_output:
 [[3696.25 3711.27 3688.57 3701.17]]
255 [D loss: 0.601914, acc.: 59.00%] [G loss: 0.838811]
input:
 [[2578.28 2676.85 2574.57 2663.68]
 [2514.92 2538.18 2459.96 2488.65]
 [2458.54 2533.22 2455.79 2526.9 ]
 [2498.08 2522.75 2447.49 2470.5 ]
 [2614.69 2641.39 2571.15 2584.59]]
fake_output:
 [[2563.02710988 26

276 [D loss: 0.655366, acc.: 51.67%] [G loss: 0.823289]
input:
 [[3916.4  3925.99 3890.39 3916.38]
 [3920.78 3931.5  3884.94 3909.88]
 [3910.49 3918.35 3902.64 3911.23]
 [3892.59 3915.77 3892.59 3915.59]
 [3878.3  3894.56 3874.93 3886.83]]
fake_output:
 [[3934.82278855 3954.05227948 3882.54485189 3898.22007024]]
real_output:
 [[3836.66 3872.42 3836.66 3871.74]]
277 [D loss: 0.638598, acc.: 57.00%] [G loss: 0.880869]
input:
 [[4632.24 4632.24 4568.7  4577.11]
 [4637.99 4665.13 4614.75 4662.85]
 [4733.56 4744.13 4650.29 4659.03]
 [4728.59 4748.83 4706.71 4726.35]
 [4669.14 4714.13 4638.27 4713.07]]
fake_output:
 [[4735.47591259 4794.50365889 4624.04702084 4643.2355801 ]]
real_output:
 [[4655.34 4673.02 4582.24 4670.29]]
278 [D loss: 0.622762, acc.: 58.00%] [G loss: 0.847860]
input:
 [[4358.01 4372.87 4329.92 4363.8 ]
 [4368.31 4374.89 4342.09 4350.65]
 [4385.44 4415.88 4360.59 4361.19]
 [4406.51 4412.02 4386.22 4391.34]
 [4383.73 4429.97 4383.73 4399.76]]
fake_output:
 [[4409.84599463 44

300 [D loss: 0.624315, acc.: 59.00%] [G loss: 0.982402]
input:
 [[4124.71 4131.76 4114.82 4127.99]
 [4096.11 4129.48 4095.51 4128.8 ]
 [4089.95 4098.19 4082.54 4097.17]
 [4074.29 4083.13 4068.31 4079.95]
 [4075.57 4086.23 4068.14 4073.94]]
fake_output:
 [[4132.27058537 4149.54187948 4066.06723236 4077.1237316 ]]
real_output:
 [[4034.44 4083.42 4034.44 4077.91]]
301 [D loss: 0.642153, acc.: 59.50%] [G loss: 1.011437]
input:
 [[3392.51 3399.54 3369.66 3374.85]
 [3387.04 3395.06 3370.15 3389.78]
 [3380.86 3387.59 3379.22 3381.99]
 [3368.66 3378.51 3361.64 3372.85]
 [3372.95 3387.24 3363.35 3373.43]]
fake_output:
 [[3396.50497602 3401.7498731  3362.40163163 3372.41195283]]
real_output:
 [[3355.46 3387.89 3355.46 3380.35]]
302 [D loss: 0.630148, acc.: 61.17%] [G loss: 0.970490]
input:
 [[4642.99 4660.47 4606.52 4634.09]
 [4710.3  4710.3  4667.6  4668.97]
 [4687.64 4713.57 4670.24 4712.02]
 [4691.   4695.26 4665.98 4667.45]
 [4690.86 4705.06 4674.52 4701.21]]
fake_output:
 [[4766.98761062 47

324 [D loss: 0.539234, acc.: 72.83%] [G loss: 1.461626]
input:
 [[4406.75 4465.4  4406.75 4448.98]
 [4367.43 4416.75 4367.43 4395.64]
 [4374.45 4394.87 4347.96 4354.19]
 [4402.95 4402.95 4305.91 4357.73]
 [4469.74 4471.52 4427.76 4432.99]]
fake_output:
 [[4536.87867687 4460.88510658 4204.49776911 4323.40478788]]
real_output:
 [[4477.09 4485.87 4443.8  4473.75]]
325 [D loss: 0.549248, acc.: 68.00%] [G loss: 1.439012]
input:
 [[2344.44 2449.71 2344.44 2447.33]
 [2290.71 2300.73 2191.86 2237.4 ]
 [2431.94 2453.01 2295.56 2304.92]
 [2393.48 2466.97 2319.78 2409.39]
 [2436.5  2453.57 2280.52 2398.1 ]]
fake_output:
 [[2575.89993462 2475.99634131 2079.26573565 2213.1083711 ]]
real_output:
 [[2425.66 2553.93 2367.04 2529.19]]
326 [D loss: 0.614226, acc.: 65.50%] [G loss: 1.432446]
input:
 [[3842.51 3914.5  3842.51 3901.82]
 [3839.66 3861.08 3789.54 3811.15]
 [3915.8  3925.02 3814.04 3829.34]
 [3873.71 3928.65 3859.6  3925.43]
 [3857.07 3895.98 3805.59 3881.37]]
fake_output:
 [[3949.04118815 39

input:
 [[3234.27 3243.72 3216.17 3218.44]
 [3219.84 3241.43 3214.25 3239.41]
 [3218.58 3227.26 3200.05 3215.63]
 [3271.64 3279.99 3222.66 3235.66]
 [3254.86 3279.32 3253.1  3276.02]]
fake_output:
 [[3263.27540461 3233.70938322 3160.48951673 3221.19533494]]
real_output:
 [[3268.52 3277.29 3247.77 3257.3 ]]
348 [D loss: 0.666110, acc.: 56.33%] [G loss: 1.168985]
input:
 [[3234.27 3243.72 3216.17 3218.44]
 [3219.84 3241.43 3214.25 3239.41]
 [3218.58 3227.26 3200.05 3215.63]
 [3271.64 3279.99 3222.66 3235.66]
 [3254.86 3279.32 3253.1  3276.02]]
fake_output:
 [[3260.74836095 3235.16025381 3164.99713524 3222.76452562]]
real_output:
 [[3268.52 3277.29 3247.77 3257.3 ]]
349 [D loss: 0.610293, acc.: 59.33%] [G loss: 1.545660]
input:
 [[4490.45 4501.71 4485.66 4496.19]
 [4484.4  4492.81 4482.28 4486.23]
 [4450.29 4489.88 4450.29 4479.53]
 [4410.56 4444.35 4406.8  4441.67]
 [4382.44 4418.61 4367.73 4405.8 ]]
fake_output:
 [[4473.76457481 4449.10399734 4334.71350214 4445.83179974]]
real_output:
 

371 [D loss: 0.734798, acc.: 47.33%] [G loss: 1.061080]
input:
 [[4450.29 4489.88 4450.29 4479.53]
 [4410.56 4444.35 4406.8  4441.67]
 [4382.44 4418.61 4367.73 4405.8 ]
 [4440.94 4454.32 4397.59 4400.27]
 [4462.12 4462.12 4417.83 4448.08]]
fake_output:
 [[4411.42032477 4411.03572073 4327.69308291 4433.64156334]]
real_output:
 [[4461.65 4480.26 4437.66 4479.71]]
372 [D loss: 0.716547, acc.: 52.17%] [G loss: 1.248381]
input:
 [[3851.93 3903.76 3851.93 3875.44]
 [3844.39 3881.06 3819.25 3821.35]
 [3793.58 3851.69 3730.19 3841.94]
 [3818.53 3843.67 3723.34 3768.47]
 [3863.99 3874.47 3818.86 3819.72]]
fake_output:
 [[3821.6291235  3835.35122991 3645.67637641 3822.87331122]]
real_output:
 [[3903.64 3906.41 3868.57 3870.29]]
373 [D loss: 0.735476, acc.: 47.00%] [G loss: 1.131378]
input:
 [[3836.83 3836.83 3732.48 3750.77]
 [3862.96 3870.9  3847.78 3849.62]
 [3851.68 3859.23 3797.16 3855.36]
 [3844.24 3852.31 3830.41 3841.47]
 [3857.46 3861.45 3845.05 3853.07]]
fake_output:
 [[3842.48473397 38

input:
 [[3764.61 3769.99 3662.71 3700.65]
 [3733.27 3760.2  3726.88 3756.07]
 [3736.19 3744.63 3730.21 3732.04]
 [3750.01 3756.12 3723.31 3727.04]
 [3723.03 3740.51 3723.03 3735.36]]
fake_output:
 [[3704.5025817  3718.08272633 3628.35119979 3720.30048155]]
real_output:
 [[3694.03 3703.82 3689.32 3703.06]]
395 [D loss: 0.791732, acc.: 41.33%] [G loss: 1.256929]
input:
 [[3357.38 3362.27 3292.4  3319.47]
 [3346.86 3375.17 3328.82 3357.01]
 [3411.23 3428.92 3384.45 3385.49]
 [3407.73 3419.48 3389.25 3401.2 ]
 [3363.56 3402.93 3363.56 3383.54]]
fake_output:
 [[3311.35467754 3313.50730563 3235.86380704 3352.30290733]]
real_output:
 [[3352.7  3368.95 3310.47 3340.97]]
396 [D loss: 0.806159, acc.: 41.00%] [G loss: 1.033442]
input:
 [[3071.04 3088.42 2984.47 3041.31]
 [3123.53 3123.53 2999.49 3002.1 ]
 [3213.42 3223.27 3181.49 3190.14]
 [3213.32 3222.71 3193.11 3207.18]
 [3199.92 3233.13 3196.   3232.39]]
fake_output:
 [[3020.63053208 2980.67694033 2808.02427708 3074.87499354]]
real_output:
 

418 [D loss: 0.821073, acc.: 39.67%] [G loss: 1.131536]
input:
 [[4534.48 4545.85 4524.66 4536.95]
 [4528.8  4537.11 4522.02 4524.09]
 [4529.75 4531.39 4515.8  4522.68]
 [4513.76 4537.36 4513.76 4528.79]
 [4474.1  4513.33 4474.1  4509.37]]
fake_output:
 [[4427.27219574 4482.81910598 4457.21255074 4503.98624928]]
real_output:
 [[4493.75 4495.9  4468.99 4470.  ]]
419 [D loss: 0.836101, acc.: 39.00%] [G loss: 1.279643]
input:
 [[2457.77 2571.42 2407.53 2475.56]
 [2344.44 2449.71 2344.44 2447.33]
 [2290.71 2300.73 2191.86 2237.4 ]
 [2431.94 2453.01 2295.56 2304.92]
 [2393.48 2466.97 2319.78 2409.39]]
fake_output:
 [[2186.40310131 2119.87637878 2151.63219871 2211.3007228 ]]
real_output:
 [[2436.5  2453.57 2280.52 2398.1 ]]
420 [D loss: 0.846207, acc.: 37.17%] [G loss: 1.091920]
input:
 [[4179.8  4180.81 4150.47 4163.26]
 [4174.14 4191.31 4170.75 4185.47]
 [4139.76 4173.49 4139.76 4170.42]
 [4141.58 4151.69 4120.87 4124.66]
 [4130.1  4148.   4124.43 4141.59]]
fake_output:
 [[4085.39923883 41

441 [D loss: 0.824320, acc.: 40.33%] [G loss: 1.047437]
input:
 [[4429.07 4440.82 4429.07 4436.52]
 [4408.86 4429.76 4408.86 4429.1 ]
 [4415.95 4416.17 4400.23 4402.66]
 [4392.74 4423.79 4373.   4423.15]
 [4406.86 4422.18 4384.81 4387.16]]
fake_output:
 [[4356.90989359 4386.71387403 4360.93030611 4348.62505919]]
real_output:
 [[4395.12 4412.25 4389.65 4395.26]]
442 [D loss: 0.818508, acc.: 39.00%] [G loss: 1.028456]
input:
 [[4319.57 4365.57 4290.49 4363.55]
 [4309.87 4369.23 4309.87 4345.72]
 [4348.84 4355.51 4278.94 4300.46]
 [4317.16 4375.19 4288.52 4357.04]
 [4370.67 4382.55 4306.24 4307.54]]
fake_output:
 [[4229.910912   4326.67298503 4272.92863397 4237.8825327 ]]
real_output:
 [[4362.41 4385.57 4355.08 4359.46]]
443 [D loss: 0.816403, acc.: 44.17%] [G loss: 1.135724]
input:
 [[4437.77 4439.39 4424.74 4432.35]
 [4429.07 4440.82 4429.07 4436.52]
 [4408.86 4429.76 4408.86 4429.1 ]
 [4415.95 4416.17 4400.23 4402.66]
 [4392.74 4423.79 4373.   4423.15]]
fake_output:
 [[4357.48835535 43

465 [D loss: 0.777512, acc.: 46.00%] [G loss: 1.158627]
input:
 [[3140.29 3155.53 3083.11 3097.74]
 [3101.64 3120.   3093.51 3115.34]
 [3136.13 3141.16 3108.03 3113.49]
 [3131.   3153.45 3076.06 3124.74]
 [2993.76 3079.76 2965.66 3066.59]]
fake_output:
 [[2836.56497223 3005.50198981 2971.75517754 2998.21523024]]
real_output:
 [[3071.04 3088.42 2984.47 3041.31]]
466 [D loss: 0.798925, acc.: 49.00%] [G loss: 1.168391]
input:
 [[4317.16 4375.19 4288.52 4357.04]
 [4370.67 4382.55 4306.24 4307.54]
 [4362.41 4385.57 4355.08 4359.46]
 [4419.54 4419.54 4346.33 4352.63]
 [4442.12 4457.3  4436.19 4443.11]]
fake_output:
 [[4195.71883383 4283.28121432 4268.46793358 4169.02043765]]
real_output:
 [[4438.04 4463.12 4430.27 4455.48]]
467 [D loss: 0.742518, acc.: 52.50%] [G loss: 1.116225]
input:
 [[3114.4  3115.01 3032.13 3050.33]
 [3138.7  3154.9  3127.12 3131.29]
 [3094.42 3120.92 3079.39 3117.86]
 [3140.29 3155.53 3083.11 3097.74]
 [3101.64 3120.   3093.51 3115.34]]
fake_output:
 [[3039.45091066 30

input:
 [[4642.99 4660.47 4606.52 4634.09]
 [4710.3  4710.3  4667.6  4668.97]
 [4687.64 4713.57 4670.24 4712.02]
 [4691.   4695.26 4665.98 4667.45]
 [4690.86 4705.06 4674.52 4701.21]]
fake_output:
 [[4598.7271701  4637.52432977 4626.4356902  4542.12165005]]
real_output:
 [[4631.97 4694.04 4631.97 4686.75]]
489 [D loss: 0.728313, acc.: 52.33%] [G loss: 1.116593]
input:
 [[3910.49 3918.35 3902.64 3911.23]
 [3892.59 3915.77 3892.59 3915.59]
 [3878.3  3894.56 3874.93 3886.83]
 [3836.66 3872.42 3836.66 3871.74]
 [3840.27 3847.51 3816.68 3830.17]]
fake_output:
 [[3745.14271832 3797.25149306 3811.70694001 3700.55200736]]
real_output:
 [[3791.84 3843.09 3791.84 3826.31]]
490 [D loss: 0.709815, acc.: 54.83%] [G loss: 1.172442]
input:
 [[3918.5  3933.61 3900.43 3931.33]
 [3939.61 3950.43 3923.85 3932.59]
 [3911.65 3937.23 3905.78 3934.83]
 [3916.4  3925.99 3890.39 3916.38]
 [3920.78 3931.5  3884.94 3909.88]]
fake_output:
 [[3882.50623456 3909.65960818 3881.85457875 3870.94217915]]
real_output:
 

511 [D loss: 0.656605, acc.: 57.83%] [G loss: 1.167335]
input:
 [[4701.48 4714.92 4694.39 4701.7 ]
 [4699.26 4718.5  4681.32 4697.53]
 [4662.93 4683.   4662.59 4680.06]
 [4630.65 4663.46 4621.19 4660.57]
 [4613.34 4635.15 4613.34 4630.65]]
fake_output:
 [[4543.14731794 4602.60472212 4605.2288496  4541.30155559]]
real_output:
 [[4610.62 4620.34 4595.06 4613.67]]
512 [D loss: 0.654259, acc.: 59.83%] [G loss: 1.231069]
input:
 [[3338.94 3369.1  3323.69 3348.44]
 [3385.87 3397.18 3361.39 3380.8 ]
 [3341.21 3393.56 3340.47 3363.  ]
 [3350.92 3357.92 3327.54 3335.47]
 [3333.9  3360.74 3332.91 3351.6 ]]
fake_output:
 [[3281.52511456 3328.56310717 3312.05061378 3265.3282603 ]]
real_output:
 [[3236.66 3306.88 3228.44 3298.46]]
513 [D loss: 0.636356, acc.: 60.83%] [G loss: 1.278576]
input:
 [[3323.17 3351.03 3318.14 3349.16]
 [3317.37 3330.77 3317.37 3327.77]
 [3289.92 3306.84 3286.37 3306.51]
 [3288.26 3302.73 3284.53 3294.61]
 [3270.45 3272.17 3220.26 3271.12]]
fake_output:
 [[3227.24908349 32

input:
 [[3155.29 3182.59 3155.29 3179.72]
 [3143.64 3165.81 3124.52 3130.01]
 [3105.92 3128.44 3101.17 3115.86]
 [3050.2  3111.51 3047.83 3100.29]
 [3018.59 3053.89 2999.74 3053.24]]
fake_output:
 [[2959.778626   3031.88688257 2987.46929871 2937.56158381]]
real_output:
 [[3073.2  3073.73 3004.63 3009.05]]
535 [D loss: 0.653819, acc.: 60.33%] [G loss: 1.192193]
input:
 [[3610.31 3623.11 3588.68 3609.53]
 [3600.16 3628.51 3600.16 3626.91]
 [3552.57 3593.66 3552.57 3585.15]
 [3562.67 3569.02 3518.58 3537.01]
 [3563.22 3581.16 3557.   3572.66]]
fake_output:
 [[3519.81624304 3550.2172927  3514.52385363 3453.96029186]]
real_output:
 [[3543.26 3557.22 3511.91 3545.53]]
536 [D loss: 0.587806, acc.: 65.50%] [G loss: 1.226300]
input:
 [[3803.14 3817.86 3789.02 3799.61]
 [3815.05 3826.69 3783.6  3824.68]
 [3764.71 3811.55 3764.71 3803.79]
 [3712.2  3783.04 3705.34 3748.14]
 [3698.02 3737.83 3695.07 3726.86]]
fake_output:
 [[3669.49136845 3739.35503337 3693.17904399 3671.1879334 ]]
real_output:
 

557 [D loss: 0.585000, acc.: 68.00%] [G loss: 1.181980]
input:
 [[3885.55 3902.92 3874.71 3876.5 ]
 [3921.16 3930.41 3903.07 3906.71]
 [3915.86 3921.98 3885.03 3913.97]
 [3918.5  3933.61 3900.43 3931.33]
 [3939.61 3950.43 3923.85 3932.59]]
fake_output:
 [[3885.64467776 3902.33393008 3869.7115752  3854.36554625]]
real_output:
 [[3911.65 3937.23 3905.78 3934.83]]
558 [D loss: 0.591111, acc.: 66.83%] [G loss: 1.216359]
input:
 [[4479.33 4485.68 4435.46 4443.05]
 [4474.81 4492.99 4445.7  4468.73]
 [4506.92 4520.47 4457.66 4458.58]
 [4513.02 4529.9  4492.07 4493.28]
 [4518.09 4521.79 4493.95 4514.07]]
fake_output:
 [[4461.59498274 4476.80613594 4417.5609493  4379.99115894]]
real_output:
 [[4535.38 4535.38 4513.   4520.03]]
559 [D loss: 0.643006, acc.: 60.33%] [G loss: 1.079640]
input:
 [[3840.27 3847.51 3816.68 3830.17]
 [3791.84 3843.09 3791.84 3826.31]
 [3731.17 3784.32 3725.62 3773.86]
 [3778.05 3778.05 3694.12 3714.24]
 [3755.75 3830.5  3755.75 3787.38]]
fake_output:
 [[3714.47911852 37

input:
 [[3698.02 3737.83 3695.07 3726.86]
 [3764.61 3769.99 3662.71 3700.65]
 [3733.27 3760.2  3726.88 3756.07]
 [3736.19 3744.63 3730.21 3732.04]
 [3750.01 3756.12 3723.31 3727.04]]
fake_output:
 [[3704.94134802 3737.82958907 3662.90701059 3692.07260528]]
real_output:
 [[3723.03 3740.51 3723.03 3735.36]]
581 [D loss: 0.671199, acc.: 56.83%] [G loss: 1.026633]
input:
 [[2794.54 2852.8  2766.64 2852.5 ]
 [2865.86 2874.14 2793.15 2820.  ]
 [2939.5  2945.82 2869.59 2870.12]
 [2915.46 2944.25 2903.44 2930.32]
 [2908.83 2932.16 2902.88 2929.8 ]]
fake_output:
 [[2785.07871981 2836.83614729 2695.01877767 2727.45488534]]
real_output:
 [[2878.26 2901.92 2876.48 2881.19]]
582 [D loss: 0.609345, acc.: 64.67%] [G loss: 0.978929]
input:
 [[4580.22 4584.57 4551.66 4551.68]
 [4578.69 4598.53 4569.17 4574.79]
 [4553.69 4572.62 4537.36 4566.48]
 [4546.12 4559.67 4524.   4544.9 ]
 [4532.24 4551.44 4526.89 4549.78]]
fake_output:
 [[4524.77730953 4545.67069215 4504.7005881  4526.46656047]]
real_output:
 

input:
 [[3915.8  3925.02 3814.04 3829.34]
 [3873.71 3928.65 3859.6  3925.43]
 [3857.07 3895.98 3805.59 3881.37]
 [3885.55 3902.92 3874.71 3876.5 ]
 [3921.16 3930.41 3903.07 3906.71]]
fake_output:
 [[3858.22361253 3897.58540471 3790.93552094 3835.67991417]]
real_output:
 [[3915.86 3921.98 3885.03 3913.97]]
604 [D loss: 0.605661, acc.: 62.50%] [G loss: 0.948904]
input:
 [[3815.05 3826.69 3783.6  3824.68]
 [3764.71 3811.55 3764.71 3803.79]
 [3712.2  3783.04 3705.34 3748.14]
 [3698.02 3737.83 3695.07 3726.86]
 [3764.61 3769.99 3662.71 3700.65]]
fake_output:
 [[3682.89251416 3739.32568965 3638.02560301 3678.56238875]]
real_output:
 [[3733.27 3760.2  3726.88 3756.07]]
605 [D loss: 0.591702, acc.: 64.17%] [G loss: 0.980209]
input:
 [[2854.65 2887.72 2852.89 2878.48]
 [2812.64 2842.71 2791.76 2836.74]
 [2810.42 2844.9  2794.26 2797.8 ]
 [2787.89 2815.1  2775.95 2799.31]
 [2784.81 2785.54 2727.1  2736.56]]
fake_output:
 [[2761.00268942 2773.3757901  2670.21206568 2674.78586847]]
real_output:
 

input:
 [[4185.14 4201.53 4181.78 4183.18]
 [4188.25 4193.35 4176.22 4186.72]
 [4185.03 4194.19 4182.36 4187.62]
 [4138.78 4194.17 4138.78 4180.17]
 [4170.46 4179.57 4123.69 4134.98]]
fake_output:
 [[4144.04088207 4181.9474356  4108.47857308 4147.40180302]]
real_output:
 [[4128.42 4175.02 4126.35 4173.42]]
627 [D loss: 0.637001, acc.: 58.33%] [G loss: 1.018082]
input:
 [[2878.26 2901.92 2876.48 2881.19]
 [2883.14 2891.11 2847.65 2848.42]
 [2868.88 2898.23 2863.55 2868.44]
 [2815.01 2844.24 2797.85 2842.74]
 [2869.09 2869.09 2821.61 2830.71]]
fake_output:
 [[2811.79916935 2843.99545118 2773.23846017 2823.20121501]]
real_output:
 [[2930.91 2930.91 2892.47 2912.43]]
628 [D loss: 0.599208, acc.: 63.33%] [G loss: 0.907035]
input:
 [[4474.81 4492.99 4445.7  4468.73]
 [4506.92 4520.47 4457.66 4458.58]
 [4513.02 4529.9  4492.07 4493.28]
 [4518.09 4521.79 4493.95 4514.07]
 [4535.38 4535.38 4513.   4520.03]]
fake_output:
 [[4475.90180795 4499.47058746 4431.81379919 4460.83138345]]
real_output:
 

649 [D loss: 0.621170, acc.: 60.33%] [G loss: 0.929732]
input:
 [[4139.76 4173.49 4139.76 4170.42]
 [4141.58 4151.69 4120.87 4124.66]
 [4130.1  4148.   4124.43 4141.59]
 [4124.71 4131.76 4114.82 4127.99]
 [4096.11 4129.48 4095.51 4128.8 ]]
fake_output:
 [[4100.98475406 4127.20507257 4093.45807094 4127.4393025 ]]
real_output:
 [[4089.95 4098.19 4082.54 4097.17]]
650 [D loss: 0.607095, acc.: 60.50%] [G loss: 0.904299]
input:
 [[3713.65 3725.12 3710.87 3722.48]
 [3696.25 3711.27 3688.57 3701.17]
 [3666.41 3695.29 3659.62 3694.62]
 [3675.27 3697.61 3645.84 3647.49]
 [3656.08 3665.91 3633.4  3663.46]]
fake_output:
 [[3644.7378144  3672.97772385 3611.33670235 3665.01444357]]
real_output:
 [[3659.13 3678.49 3645.18 3668.1 ]]
651 [D loss: 0.639333, acc.: 60.17%] [G loss: 0.935997]
input:
 [[4659.39 4664.55 4648.31 4649.27]
 [4670.26 4684.85 4630.86 4646.71]
 [4707.25 4708.53 4670.87 4685.25]
 [4701.48 4714.92 4694.39 4701.7 ]
 [4699.26 4718.5  4681.32 4697.53]]
fake_output:
 [[4649.31117782 46

input:
 [[3152.47 3186.82 3136.22 3185.04]
 [3176.17 3179.78 3115.7  3152.05]
 [3153.07 3171.8  3136.53 3169.94]
 [3166.44 3184.15 3142.93 3145.32]
 [3155.29 3182.59 3155.29 3179.72]]
fake_output:
 [[3144.63762008 3174.12980949 3108.73393355 3158.77801197]]
real_output:
 [[3143.64 3165.81 3124.52 3130.01]]
673 [D loss: 0.667397, acc.: 58.50%] [G loss: 0.856525]
input:
 [[3851.68 3859.23 3797.16 3855.36]
 [3844.24 3852.31 3830.41 3841.47]
 [3857.46 3861.45 3845.05 3853.07]
 [3816.22 3859.75 3816.22 3851.85]
 [3781.88 3804.53 3780.37 3798.91]]
fake_output:
 [[3782.91109013 3822.10444876 3771.16380666 3832.89551022]]
real_output:
 [[3788.73 3788.73 3749.62 3768.25]]
674 [D loss: 0.618180, acc.: 61.00%] [G loss: 0.853720]
input:
 [[2578.28 2676.85 2574.57 2663.68]
 [2514.92 2538.18 2459.96 2488.65]
 [2458.54 2533.22 2455.79 2526.9 ]
 [2498.08 2522.75 2447.49 2470.5 ]
 [2614.69 2641.39 2571.15 2584.59]]
fake_output:
 [[2380.62732812 2483.92479031 2318.31494716 2493.64471668]]
real_output:
 

695 [D loss: 0.614818, acc.: 60.83%] [G loss: 0.925301]
input:
 [[2909.96 2921.15 2860.71 2863.39]
 [2854.65 2887.72 2852.89 2878.48]
 [2812.64 2842.71 2791.76 2836.74]
 [2810.42 2844.9  2794.26 2797.8 ]
 [2787.89 2815.1  2775.95 2799.31]]
fake_output:
 [[2741.15445325 2816.22042684 2734.72802703 2831.84333312]]
real_output:
 [[2784.81 2785.54 2727.1  2736.56]]
696 [D loss: 0.639265, acc.: 61.83%] [G loss: 0.954545]
input:
 [[3781.88 3804.53 3780.37 3798.91]
 [3788.73 3788.73 3749.62 3768.25]
 [3814.98 3823.6  3792.86 3795.54]
 [3802.23 3820.96 3791.5  3809.84]
 [3801.62 3810.78 3776.51 3801.19]]
fake_output:
 [[3773.61831094 3795.2952646  3744.27334478 3793.8313447 ]]
real_output:
 [[3803.14 3817.86 3789.02 3799.61]]
697 [D loss: 0.611653, acc.: 61.83%] [G loss: 0.907441]
input:
 [[3199.92 3233.13 3196.   3232.39]
 [3163.84 3211.72 3163.84 3193.93]
 [3111.56 3128.91 3090.41 3112.35]
 [3098.9  3130.94 3098.9  3122.87]
 [3064.78 3081.07 3051.64 3080.82]]
fake_output:
 [[3058.50606186 31

719 [D loss: 0.589487, acc.: 65.33%] [G loss: 1.011681]
input:
 [[4255.28 4257.16 4238.35 4246.59]
 [4248.31 4255.59 4234.07 4255.15]
 [4242.9  4248.38 4232.25 4247.44]
 [4228.56 4249.74 4220.34 4239.18]
 [4232.99 4237.09 4218.74 4219.55]]
fake_output:
 [[4225.7189328  4242.87973897 4215.48787989 4242.75643042]]
real_output:
 [[4233.81 4236.74 4208.41 4227.26]]
720 [D loss: 0.571887, acc.: 68.00%] [G loss: 1.008815]
input:
 [[4788.64 4804.06 4778.08 4793.06]
 [4795.49 4807.02 4780.04 4786.35]
 [4733.99 4791.49 4733.99 4791.19]
 [4703.96 4740.74 4703.96 4725.79]
 [4650.36 4697.67 4645.53 4696.56]]
fake_output:
 [[4579.16790912 4717.61347916 4596.60732649 4763.99199195]]
real_output:
 [[4594.96 4651.14 4583.16 4649.23]]
721 [D loss: 0.589219, acc.: 67.33%] [G loss: 1.038723]
input:
 [[3675.27 3697.61 3645.84 3647.49]
 [3656.08 3665.91 3633.4  3663.46]
 [3659.13 3678.49 3645.18 3668.1 ]
 [3705.98 3712.39 3660.54 3672.82]
 [3683.05 3708.45 3678.83 3702.25]]
fake_output:
 [[3620.33628374 36

742 [D loss: 0.549081, acc.: 72.00%] [G loss: 1.046972]
input:
 [[4446.08 4461.77 4435.96 4460.83]
 [4442.18 4449.44 4436.42 4447.7 ]
 [4435.79 4445.21 4430.03 4436.75]
 [4437.77 4439.39 4424.74 4432.35]
 [4429.07 4440.82 4429.07 4436.52]]
fake_output:
 [[4419.42976482 4436.51240124 4417.99912674 4443.7243699 ]]
real_output:
 [[4408.86 4429.76 4408.86 4429.1 ]]
743 [D loss: 0.556813, acc.: 70.50%] [G loss: 1.029543]
input:
 [[4191.43 4204.39 4167.93 4192.85]
 [4206.82 4217.37 4198.27 4208.12]
 [4216.52 4234.12 4197.59 4202.04]
 [4210.77 4218.36 4203.57 4204.11]
 [4201.94 4213.38 4197.78 4200.88]]
fake_output:
 [[4190.84311921 4209.27856641 4173.37491874 4202.37471037]]
real_output:
 [[4191.59 4202.61 4184.11 4195.99]]
744 [D loss: 0.570103, acc.: 67.33%] [G loss: 1.049298]
input:
 [[4532.42 4541.45 4521.3  4535.43]
 [4534.48 4545.85 4524.66 4536.95]
 [4528.8  4537.11 4522.02 4524.09]
 [4529.75 4531.39 4515.8  4522.68]
 [4513.76 4537.36 4513.76 4528.79]]
fake_output:
 [[4511.54839741 45

765 [D loss: 0.556079, acc.: 72.50%] [G loss: 1.121989]
input:
 [[3815.05 3826.69 3783.6  3824.68]
 [3764.71 3811.55 3764.71 3803.79]
 [3712.2  3783.04 3705.34 3748.14]
 [3698.02 3737.83 3695.07 3726.86]
 [3764.61 3769.99 3662.71 3700.65]]
fake_output:
 [[3597.06167114 3739.6704334  3578.94819758 3753.13235069]]
real_output:
 [[3733.27 3760.2  3726.88 3756.07]]
766 [D loss: 0.536230, acc.: 73.83%] [G loss: 1.062801]
input:
 [[3911.65 3937.23 3905.78 3934.83]
 [3916.4  3925.99 3890.39 3916.38]
 [3920.78 3931.5  3884.94 3909.88]
 [3910.49 3918.35 3902.64 3911.23]
 [3892.59 3915.77 3892.59 3915.59]]
fake_output:
 [[3899.12507854 3920.33676897 3886.99360909 3918.11589383]]
real_output:
 [[3878.3  3894.56 3874.93 3886.83]]
767 [D loss: 0.559119, acc.: 70.00%] [G loss: 1.106303]
input:
 [[3942.96 3970.08 3923.54 3968.94]
 [3924.52 3944.99 3915.21 3943.34]
 [3915.54 3960.27 3915.54 3939.34]
 [3891.99 3917.35 3885.73 3898.81]
 [3851.93 3903.76 3851.93 3875.44]]
fake_output:
 [[3806.48157358 39

input:
 [[4490.45 4501.71 4485.66 4496.19]
 [4484.4  4492.81 4482.28 4486.23]
 [4450.29 4489.88 4450.29 4479.53]
 [4410.56 4444.35 4406.8  4441.67]
 [4382.44 4418.61 4367.73 4405.8 ]]
fake_output:
 [[4368.68946125 4432.44943229 4377.95616902 4454.87842392]]
real_output:
 [[4440.94 4454.32 4397.59 4400.27]]
789 [D loss: 0.549870, acc.: 71.17%] [G loss: 1.029401]
input:
 [[3407.73 3419.48 3389.25 3401.2 ]
 [3363.56 3402.93 3363.56 3383.54]
 [3352.7  3368.95 3310.47 3340.97]
 [3412.56 3425.55 3329.25 3339.19]
 [3369.82 3424.77 3366.84 3398.96]]
fake_output:
 [[3345.39976781 3387.44411996 3318.80963399 3370.2112225 ]]
real_output:
 [[3371.88 3379.97 3329.27 3331.84]]
790 [D loss: 0.570325, acc.: 68.17%] [G loss: 1.052297]
input:
 [[3666.41 3695.29 3659.62 3694.62]
 [3675.27 3697.61 3645.84 3647.49]
 [3656.08 3665.91 3633.4  3663.46]
 [3659.13 3678.49 3645.18 3668.1 ]
 [3705.98 3712.39 3660.54 3672.82]]
fake_output:
 [[3624.26087664 3662.34100247 3625.24369184 3660.92174906]]
real_output:
 

input:
 [[4284.9  4292.14 4274.67 4290.61]
 [4274.45 4286.12 4271.16 4280.7 ]
 [4256.97 4271.28 4256.97 4266.49]
 [4249.27 4256.6  4241.43 4241.84]
 [4224.61 4255.84 4217.27 4246.44]]
fake_output:
 [[4194.95752059 4231.77759149 4189.11964304 4227.69373061]]
real_output:
 [[4173.4  4226.24 4173.4  4224.79]]
812 [D loss: 0.564404, acc.: 67.83%] [G loss: 0.984048]
input:
 [[4356.46 4356.46 4314.37 4343.54]
 [4326.6  4355.43 4326.6  4352.34]
 [4300.73 4320.66 4300.73 4319.94]
 [4290.65 4302.43 4287.96 4297.5 ]
 [4293.21 4300.52 4287.04 4291.8 ]]
fake_output:
 [[4260.40065902 4280.48508283 4281.94406644 4301.77506879]]
real_output:
 [[4284.9  4292.14 4274.67 4290.61]]
813 [D loss: 0.574998, acc.: 65.50%] [G loss: 0.979001]
input:
 [[4628.75 4672.95 4625.26 4655.27]
 [4664.63 4664.63 4585.43 4594.62]
 [4675.78 4702.87 4659.89 4701.46]
 [4678.48 4699.39 4652.66 4690.7 ]
 [4712.   4743.83 4682.17 4682.94]]
fake_output:
 [[4604.47018853 4628.47495255 4571.13539173 4610.22914313]]
real_output:
 

834 [D loss: 0.614420, acc.: 59.33%] [G loss: 0.876378]
input:
 [[2782.46 2782.46 2721.17 2761.63]
 [2776.99 2818.57 2762.36 2789.82]
 [2685.   2760.75 2663.3  2749.98]
 [2738.65 2756.89 2657.67 2659.41]
 [2578.28 2676.85 2574.57 2663.68]]
fake_output:
 [[2575.52808575 2589.53006445 2542.21826376 2577.21175724]]
real_output:
 [[2514.92 2538.18 2459.96 2488.65]]
835 [D loss: 0.639377, acc.: 58.17%] [G loss: 0.930387]
input:
 [[4348.84 4355.51 4278.94 4300.46]
 [4317.16 4375.19 4288.52 4357.04]
 [4370.67 4382.55 4306.24 4307.54]
 [4362.41 4385.57 4355.08 4359.46]
 [4419.54 4419.54 4346.33 4352.63]]
fake_output:
 [[4312.10472511 4320.04070626 4266.23189257 4278.72626854]]
real_output:
 [[4442.12 4457.3  4436.19 4443.11]]
836 [D loss: 0.613054, acc.: 64.00%] [G loss: 0.916634]
input:
 [[2878.26 2901.92 2876.48 2881.19]
 [2883.14 2891.11 2847.65 2848.42]
 [2868.88 2898.23 2863.55 2868.44]
 [2815.01 2844.24 2797.85 2842.74]
 [2869.09 2869.09 2821.61 2830.71]]
fake_output:
 [[2832.30961834 28

input:
 [[3152.47 3186.82 3136.22 3185.04]
 [3176.17 3179.78 3115.7  3152.05]
 [3153.07 3171.8  3136.53 3169.94]
 [3166.44 3184.15 3142.93 3145.32]
 [3155.29 3182.59 3155.29 3179.72]]
fake_output:
 [[3153.07369021 3159.26457535 3113.05727374 3111.46561333]]
real_output:
 [[3143.64 3165.81 3124.52 3130.01]]
858 [D loss: 0.656786, acc.: 55.50%] [G loss: 0.913686]
input:
 [[3793.58 3851.69 3730.19 3841.94]
 [3818.53 3843.67 3723.34 3768.47]
 [3863.99 3874.47 3818.86 3819.72]
 [3903.64 3906.41 3868.57 3870.29]
 [3842.51 3914.5  3842.51 3901.82]]
fake_output:
 [[3817.83691139 3787.58902548 3738.71876821 3739.8566092 ]]
real_output:
 [[3839.66 3861.08 3789.54 3811.15]]
859 [D loss: 0.671321, acc.: 53.83%] [G loss: 0.947207]
input:
 [[4159.18 4159.18 4118.38 4134.94]
 [4179.8  4180.81 4150.47 4163.26]
 [4174.14 4191.31 4170.75 4185.47]
 [4139.76 4173.49 4139.76 4170.42]
 [4141.58 4151.69 4120.87 4124.66]]
fake_output:
 [[4162.32075808 4167.84061175 4140.13255294 4153.43460929]]
real_output:
 

input:
 [[3385.87 3397.18 3361.39 3380.8 ]
 [3341.21 3393.56 3340.47 3363.  ]
 [3350.92 3357.92 3327.54 3335.47]
 [3333.9  3360.74 3332.91 3351.6 ]
 [3236.66 3306.88 3228.44 3298.46]]
fake_output:
 [[3351.21940772 3337.0515804  3312.90363283 3332.11178325]]
real_output:
 [[3226.14 3278.7  3209.45 3246.59]]
881 [D loss: 0.710257, acc.: 53.33%] [G loss: 0.987503]
input:
 [[4170.46 4179.57 4123.69 4134.98]
 [4128.42 4175.02 4126.35 4173.42]
 [4159.18 4159.18 4118.38 4134.94]
 [4179.8  4180.81 4150.47 4163.26]
 [4174.14 4191.31 4170.75 4185.47]]
fake_output:
 [[4166.40158615 4128.22274007 4115.47100433 4083.59700043]]
real_output:
 [[4139.76 4173.49 4139.76 4170.42]]
882 [D loss: 0.746450, acc.: 48.33%] [G loss: 0.913892]
input:
 [[3213.42 3223.27 3181.49 3190.14]
 [3213.32 3222.71 3193.11 3207.18]
 [3199.92 3233.13 3196.   3232.39]
 [3163.84 3211.72 3163.84 3193.93]
 [3111.56 3128.91 3090.41 3112.35]]
fake_output:
 [[3192.92169302 3170.71667493 3160.19762267 3168.73872855]]
real_output:
 

input:
 [[2948.05 2956.76 2933.59 2955.45]
 [2969.95 2978.5  2938.57 2948.51]
 [2953.63 2980.29 2953.63 2971.61]
 [2948.59 2964.21 2922.35 2922.94]
 [2913.86 2968.09 2913.86 2953.91]]
fake_output:
 [[2994.06362151 2918.61129021 2924.52492806 2878.29187183]]
real_output:
 [[2829.95 2865.01 2816.78 2863.7 ]]
904 [D loss: 0.715709, acc.: 53.83%] [G loss: 0.954208]
input:
 [[4188.25 4193.35 4176.22 4186.72]
 [4185.03 4194.19 4182.36 4187.62]
 [4138.78 4194.17 4138.78 4180.17]
 [4170.46 4179.57 4123.69 4134.98]
 [4128.42 4175.02 4126.35 4173.42]]
fake_output:
 [[4191.31502193 4178.51178546 4163.56444163 4164.32137971]]
real_output:
 [[4159.18 4159.18 4118.38 4134.94]]
905 [D loss: 0.755926, acc.: 46.67%] [G loss: 0.944751]
input:
 [[3515.47 3527.94 3480.55 3488.67]
 [3534.01 3534.01 3500.86 3511.93]
 [3500.02 3549.85 3499.61 3534.22]
 [3459.67 3482.34 3458.07 3477.13]
 [3434.28 3447.28 3428.15 3446.83]]
fake_output:
 [[3548.30416007 3443.20107069 3486.53449595 3469.27329789]]
real_output:
 

927 [D loss: 0.925152, acc.: 44.67%] [G loss: 1.112775]
input:
 [[3213.32 3222.71 3193.11 3207.18]
 [3199.92 3233.13 3196.   3232.39]
 [3163.84 3211.72 3163.84 3193.93]
 [3111.56 3128.91 3090.41 3112.35]
 [3098.9  3130.94 3098.9  3122.87]]
fake_output:
 [[3432.38142135 3194.21456092 3412.03302765 3322.01661203]]
real_output:
 [[3064.78 3081.07 3051.64 3080.82]]
928 [D loss: 0.905032, acc.: 42.17%] [G loss: 1.048354]
input:
 [[2776.99 2818.57 2762.36 2789.82]
 [2685.   2760.75 2663.3  2749.98]
 [2738.65 2756.89 2657.67 2659.41]
 [2578.28 2676.85 2574.57 2663.68]
 [2514.92 2538.18 2459.96 2488.65]]
fake_output:
 [[2813.75639268 2782.15263931 2820.99793716 2832.24821977]]
real_output:
 [[2458.54 2533.22 2455.79 2526.9 ]]
929 [D loss: 0.884414, acc.: 43.33%] [G loss: 1.168148]
input:
 [[3367.27 3409.57 3367.27 3408.63]
 [3338.94 3369.1  3323.69 3348.44]
 [3385.87 3397.18 3361.39 3380.8 ]
 [3341.21 3393.56 3340.47 3363.  ]
 [3350.92 3357.92 3327.54 3335.47]]
fake_output:
 [[3471.5312927  33

951 [D loss: 0.668026, acc.: 62.83%] [G loss: 3.382694]
input:
 [[3296.2  3330.14 3279.74 3310.24]
 [3293.59 3304.93 3233.94 3269.96]
 [3277.17 3341.05 3259.82 3310.11]
 [3342.48 3342.48 3268.89 3271.03]
 [3403.15 3409.51 3388.71 3390.68]]
fake_output:
 [[3421.04582404 3444.27051496 3465.85124139 3494.35217964]]
real_output:
 [[3441.42 3441.42 3364.86 3400.97]]
952 [D loss: 0.634076, acc.: 65.33%] [G loss: 2.558321]
input:
 [[3234.27 3243.72 3216.17 3218.44]
 [3219.84 3241.43 3214.25 3239.41]
 [3218.58 3227.26 3200.05 3215.63]
 [3271.64 3279.99 3222.66 3235.66]
 [3254.86 3279.32 3253.1  3276.02]]
fake_output:
 [[3363.4942249  3330.67176986 3315.11850788 3388.77894339]]
real_output:
 [[3268.52 3277.29 3247.77 3257.3 ]]
953 [D loss: 0.704980, acc.: 58.83%] [G loss: 2.835006]
input:
 [[4174.14 4191.31 4170.75 4185.47]
 [4139.76 4173.49 4139.76 4170.42]
 [4141.58 4151.69 4120.87 4124.66]
 [4130.1  4148.   4124.43 4141.59]
 [4124.71 4131.76 4114.82 4127.99]]
fake_output:
 [[4220.67131893 42

975 [D loss: 0.565144, acc.: 71.17%] [G loss: 2.086520]
input:
 [[3094.42 3120.92 3079.39 3117.86]
 [3140.29 3155.53 3083.11 3097.74]
 [3101.64 3120.   3093.51 3115.34]
 [3136.13 3141.16 3108.03 3113.49]
 [3131.   3153.45 3076.06 3124.74]]
fake_output:
 [[3216.00974288 3196.95215423 3104.19848966 3137.00007205]]
real_output:
 [[2993.76 3079.76 2965.66 3066.59]]
976 [D loss: 0.531050, acc.: 71.67%] [G loss: 2.017921]
input:
 [[3755.75 3830.5  3755.75 3787.38]
 [3836.83 3836.83 3732.48 3750.77]
 [3862.96 3870.9  3847.78 3849.62]
 [3851.68 3859.23 3797.16 3855.36]
 [3844.24 3852.31 3830.41 3841.47]]
fake_output:
 [[3866.75405137 3880.79490933 3866.90341323 3904.76518217]]
real_output:
 [[3857.46 3861.45 3845.05 3853.07]]
977 [D loss: 0.603210, acc.: 68.50%] [G loss: 2.148510]
input:
 [[3213.32 3222.71 3193.11 3207.18]
 [3199.92 3233.13 3196.   3232.39]
 [3163.84 3211.72 3163.84 3193.93]
 [3111.56 3128.91 3090.41 3112.35]
 [3098.9  3130.94 3098.9  3122.87]]
fake_output:
 [[3391.91273431 33

input:
 [[4642.99 4660.47 4606.52 4634.09]
 [4710.3  4710.3  4667.6  4668.97]
 [4687.64 4713.57 4670.24 4712.02]
 [4691.   4695.26 4665.98 4667.45]
 [4690.86 4705.06 4674.52 4701.21]]
fake_output:
 [[4779.9000526  4747.86248264 4678.04875827 4698.00747493]]
real_output:
 [[4631.97 4694.04 4631.97 4686.75]]
999 [D loss: 0.534245, acc.: 71.00%] [G loss: 1.731105]


Loading pretrained model

Installinging Mido Library

# Generating Melody
Generating random input and letting model predict output

In [143]:

random = np.random.normal(0,1,(1,5,4))

predict = lstmgan.generator(random)

print(predict)

tf.Tensor([[ 0.08106427 -6.513324   -8.422126   -9.677593  ]], shape=(1, 4), dtype=float32)


# Back to MIDI
Save generated melody back to a .mid file

In [ ]:
midler = MidiFile()
track = MidiTrack()
midler.tracks.append(track)
track.append(Message('program_change', program=2, time=0))
for x in range(16):
    track.append(Message('note_on', note=int(predict[0][x][0]), velocity=64, time=20))
    track.append(Message('note_off', note=int(predict[0][x][0]), velocity=64, time=20))
    midler.save('new_song.mid')